services:
  api:
    restart: 'no'
    build:
      context: ./api
      dockerfile: Dockerfile
    command: >
      sh -c "
        if [ \"$${RUN_TESTS_ON_START}\" = \"true\" ]; then
          npm test;
        fi;
        npm start
      "
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DB: ${MYSQL_DB}

      MIN_GAME_VERSION: ${MIN_GAME_VERSION}

      PORT: ${PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      RUN_TESTS_ON_START: ${RUN_TESTS_ON_START:-false}
  
  db:
    image: mysql:9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "-p=${MYSQL_PASS}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
      - ./api/sql/init:/docker-entrypoint-initdb.d
  
volumes:
  database: